### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by tensorstart** [faameunier/MCTSnet#1]
Hi,bro~!Could you please tell me your python version and operating system？Recently we need to reproduce the papers of mctsnet.Thank you very much

**Comment by faameunier** [comment]
Hi, sorry for the late answer.

The code ran on python 3.6 and Win 10.

**Comment by tensorstart** [comment]
Thank you for your reply, we have rewritten MCTSnet project and got the expected results



---Original---

**Comment by xiao03** [comment]
Sorry to reply to a closed issue. @tensorstart Do you plan to open-source the repo?
